apiVersion: v1
kind: Pod
metadata:
  name: migracion-kraft-1
  namespace: kafka
spec:
  containers:
  - name: migracion
    image: confluentinc/cp-server:7.6.0
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: disco-viejo
      mountPath: /mnt/viejo
      readOnly: true
    - name: disco-temp
      mountPath: /mnt/temp
  volumes:
  - name: disco-viejo
    persistentVolumeClaim:
      claimName: data0-kraftcontroller-1
  - name: disco-temp
    persistentVolumeClaim:
      claimName: data0-kraftcontroller-1-temp
