apiVersion: v1
kind: Pod
metadata:
  name: rescue-cc
  namespace: kafka
spec:
  containers:
  - name: rescue
    image: confluentinc/cp-server:7.6.0
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: disco-viejo
      mountPath: /mnt/viejo
  volumes:
  - name: disco-viejo
    persistentVolumeClaim:
      claimName: data0-controlcenter-0
