apiVersion: v1
kind: Service
metadata:
  name: hsp-cites-app-svc
  namespace: p1042
spec:
  selector:
      app: hsp-cites-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http