apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyT0RRek5EZzROekV3SGhjTk1qTXdOVEUzTVRnME1URXhXaGNOTXpNd05URTBNVGcwTVRFeApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyT0RRek5EZzROekV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRVmdTUnZnelp4b1hIUjltU3Y4QkEvbElkWmhVa0FubmtBWmxIM1I3L1AKMGhOQXVjOU1hUnJYWmxoQjdwZERZbVVLOW5xYUtDRXIwTm5SdmFYMFZ3emhvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVMxOXA1KzNQQ0lhejA5Uk12ZmNvCkRGZUtscDR3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU81VHo2WWlzZUx6K2QweXNaamNqTE5Sd2JMTmlWZWcKM1BOZEdHTElRNmdCQWlCSURvUlhQd0x6NGFtZU9EMldlcnoyUlNjeFAvbXY4RDh1cDRxK2hFUjlEQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://172.31.99.70:6443
  name: default
contexts:
- context:
    cluster: default
    namespace: for-etc
    user: formacion-access
  name: default
current-context: default
users:
- name: formacion-access
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkJmeTJYNWx0ZkhZclMxdDFHQ21qWXZidGNETHpjN2E3U2FSc3c3eVROV2cifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJmb3ItZXRjIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImZvcm1hY2lvbi1hY2Nlc3MtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZm9ybWFjaW9uLWFjY2VzcyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2Nlc3MudXBpZCI6IjY2MWNiNjQ3LTQxMjYtNDM3Ni1hYTkzLTBlM2YzOTUxOWRjYyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpmb3ItZXRjOmZvcm1hY2lvbi1hY2Nlc3MifQ.O4R0wsAQNA--z6--CTrYRAbaQviW4TVF-9Sg-q6tQ6Oq-SjwAYY0c4WMYGTTk9VwPYKugX0c6qEKy2iyIiUnIylL4ovY3Q9LPWrVDjpv2M65qqdy9DrJlaHnPy5P91l4oGN5dW2c8k4o6nBmXqgV84wsfR7ehzHpobVhU0YhROOwMmLf4cjipjGQTLUxMd0JZFqRDhtCr7kIkA1HP-cwZUIrB0IVZtwOBWefrqAzH_yGT7yP3VYrhlsxv7ITyf7LDW9RGx92lMH5h_UPJdkW-xAKSY80kvxd5tz0PgXVYFfYIyJ-AfLeupJ9cZCQMIFBWnUJGfgrhF4EoxVcgjjLWA