apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: sesiones-clinicas
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: thin-csi
