apiVersion: v1
kind: Pod
metadata:
  name: migracion-keycloak
  namespace: sesiones-clinicas
spec:
  containers:
  - name: migracion
    # Usamos una imagen base ligera de Red Hat
    image: confluentinc/cp-server:7.6.0
    command: ["/bin/sleep", "infinity"]
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: disco-viejo
      mountPath: /mnt/viejo
      readOnly: true  # Solo lectura por seguridad
    - name: disco-nuevo
      mountPath: /mnt/nuevo
  volumes:
  - name: disco-viejo
    persistentVolumeClaim:
      claimName: keycloak-sp      # El disco actual (thin)
  - name: disco-nuevo
    persistentVolumeClaim:
      claimName: keycloak-sp-csi  # El disco nuevo (thin-csi)
