# ===================================================================
# 1. GRUPOS DE VARIABLES GLOBALES
# ===================================================================

[all:vars]
;ansible_ssh_private_key_file=/ruta/a/tu/clave.pem

# Variables maestro para sistemas Linux administrables
[linux_vms:vars]
ansible_user=root
ansible_become_pass="{{ vault_pass_default }}"
;ansible_python_interpreter=/usr/bin/python3

# ===================================================================
# 2. ENTORNO DE DESARROLLO (LABORATORIO DE PRUEBAS)
# ===================================================================
[linux_des]
developmENt03 ansible_user=atos ansible_password="{{ vault_pass_atos }}" ansible_become_pass="{{ vault_pass_atos }}" ansible_python_interpreter=/usr/bin/python3.6
dokuflex01test
dwh01des
dwh02des
enigma01DEs
estimtraCK01des.santpau.es
famaafm02Des
famaapp01Des
intrahsp01des
intrahsp02des
intrahsp03des ansible_password="{{ vault_pass_intrahsp }}" ansible_become_pass="{{ vault_pass_intrahsp }}" ansible_python_interpreter=/usr/bin/python3.6
intrahsp04des ansible_password="{{ vault_pass_intrahsp }}" ansible_become_pass="{{ vault_pass_intrahsp }}"
kabisoft02 ansible_user=root ansible_password="{{ vault_pass_default }}" ansible_become_pass="{{ vault_pass_default }}"
kabisoft01 ansible_user=root ansible_password="{{ vault_pass_default }}" ansible_become_pass="{{ vault_pass_default }}"
mongodb01Des
mongodb02Des
mongodb03Des
mongodb04Des
mongodbdES
patwindb02des
sau01des ansible_user=atos ansible_become_pass="{{ vault_pass_atos }}"
sescli01DEs
setapp01DEs
setdb01dES
wdisp01dES
webapps01Des ansible_user=webapps ansible_password="{{ vault_pass_webapps }}" ansible_become_pass="{{ vault_pass_webapps }}"
webpub01DEs
webpub02DEs

# ===================================================================
# 3. ENTORNO DE PRODUCCIÓN (SANT PAU IT OPERACIONES CRÍTICAS)
# ===================================================================
[linux_prod]
activiti01 ansible_user=atos ansible_password="{{ vault_pass_atos }}" ansible_become_pass="{{ vault_pass_atos }}"
ansible01
appinfurG01 ansible_user=athenea ansible_password="{{ vault_pass_athenea }}" ansible_become_pass="{{ vault_pass_athenea }}"
app-nnn
appwmp01
arum01
atb01 ansible_host=172.31.88.204 ansible_password="{{ vault_pass_default }}"
bastion01 ansible_host=172.33.105.105 ansible_user=oke-admin ansible_password="{{ vault_pass_oke_admin }}" ansible_become_pass="{{ vault_pass_oke_admin }}"
bastion02
bastion03
BACTERIEMIES01 ansible_user=admbacteriemies01 ansible_password="{{ vault_pass_bacteriemies }}" ansible_become_pass="{{ vault_pass_bacteriemies }}"
bbddspauA01
cisco-sySLog01 ansible_password="{{ vault_pass_default }}"
codiasshSP01
codiasshSP02
commvaulT-frel.santpau.es
CRD02 ansible_user=root ansible_password="{{ vault_pass_crd02 }}"
dlab01 ansible_user=logicalis ansible_password="{{ vault_pass_default }}"
dna-backUPs
dns01
dns02
dns04
dns05
dokuflex01
dokuflex01cons.santpau.es
dwh01
dwh02
enigma01.santpau.es
enigmaprN03
estimtraCK01.santpau.es
etccons01
exhsp-prOXy-pass
exhsp-prOXy-pass-int
exhsp-prOXy-pass-int-clone ansible_host=172.31.99.82 ansible_password="{{ vault_pass_default }}" ansible_become_pass="{{ vault_pass_default }}"
famaafm02
famaapp01
foreman01
ftp01
gefact02
gestioip ansible_user=logicalis
gestionlogs ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss' ansible_password="{{ vault_pass_default }}"
gestprj01
gitlab01
gota04
kabisoft01
hspeibi01.santpau.es ansible_user=hsproot ansible_password="{{ vault_pass_hsproot }}" ansible_become_pass="{{ vault_pass_hsproot }}"
HSPEIDB01.santpau.es ansible_user=hsproot ansible_password="{{ vault_pass_hsproot }}" ansible_become_pass="{{ vault_pass_hsproot }}"
HSPEIXERo02.santpau.es ansible_user=hsproot ansible_password="{{ vault_pass_hsproot }}" ansible_become_pass="{{ vault_pass_hsproot }}" ansible_host=172.31.98.72
informesDB01
intrahsp01
intrahsp02
intrahsp03
intranetHSp04
ipquorum03 ansible_password="{{ vault_pass_ipquorum }}" ansible_host=172.31.91.189
ipquorum04 ansible_password="{{ vault_pass_ipquorum }}" ansible_host=172.31.91.190
jenkins01
jirahsp
jirahspbD
jirahspbD-test
JUMPBOXEDR01 ansible_user=root ansible_password="{{ vault_pass_jumpbox }}"
mongodb
mongodb01
mongodb02
mongodb03
mongodb04
moodle
nagios.sANtpau.es
nexus01
omaweb01.Santpau.es
openlab01
openlab05
openlab08
opsmanagER01
patwindb02
PETITSACASA01 ansible_password="{{ vault_pass_default }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
petitsacASa02 ansible_password="{{ vault_pass_default }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'# ansible_become_pass="{{ vault_pass_default }}"
pid01
piddb
pip01
pipdb
piq01
piqdb
proxy-paSS
proxypasS01
proxy-paSS-ir
puigmal
puigsacaLM
pyxisgr01.santpau.es ansible_user=installer ansible_become_pass="{{ vault_pass_pyxis }}"
QUENDAANblICK
recerca02 ansible_user=recerca ansible_become_pass="{{ vault_pass_recerca }}"
redcapapP01
redcapdb01
redis01
rman01
rman19
sapcconnECt01
sapsolmaN01
sapspa01
sapspb01
sapspe
sapspf01
sapspp01
sapspu01
sau01 ansible_user=atos ansible_become_pass="{{ vault_pass_atos }}"
scannessUS01 ansible_user=admsechsp ansible_password="{{ vault_pass_sec }}" ansible_become_pass="{{ vault_pass_sec }}"
sentry01 ansible_host=172.33.106.16
sescli01
srv-db-sTOrage-pifs
srv-web-APi-pifs
stor2rrd01
susemanaGEr01
sw-backuPS
sycai01
taonet02
tarif04
trak03
UBUNTU01 ansible_password="{{ vault_pass_atos }}" ansible_user=atos ansible_become_pass="{{ vault_pass_atos }}"
wdisp01pRO
webapps01
webir01
webir02
webpub01
webpub02
webpub03
webpub04
xicvar01
zabbix01

# ===================================================================
# 4. GRUPOS PADRE AUXILIARES (Para compatibilidad de tus playbooks antiguos)
# ===================================================================
[linux_servers:children]
linux_prod
linux_des

# ===================================================================
# 5. NODES KUBERNETES & INFRAESTRUCTURA INMUTABLE
# ===================================================================
[k8s_nodes]
dev-oke-BKf7c-master-0 ansible_host=172.33.105.27
dev-oke-BKf7c-master-1 ansible_host=172.33.105.28
dev-oke-BKf7c-master-2
dev-oke-BKf7c-worker-bktqf
dev-oke-BKf7c-worker-fvgvw
kairos02-Bqfh8-infra-lwbz7
kairos02-Bqfh8-infra-qk2cl
kairos02-Bqfh8-infra-qmkhq
kairos02-Bqfh8-master-0
kairos02-Bqfh8-master-1
kairos02-Bqfh8-master-2
kairos02-Bqfh8-worker-mdbll
kairos02-Bqfh8-worker-mlnz5
kairos02-Bqfh8-worker-rqsdw
kairos02-Bqfh8-worker-zjvgt
kairos03-Pqx27-infra-76pcv
kairos03-Pqx27-infra-dzcfc
kairos03-Pqx27-infra-m9sg7
kairos03-Pqx27-master-0
kairos03-Pqx27-master-1
kairos03-Pqx27-master-2
kairos03-Pqx27-worker-0-85hcr
kairos03-Pqx27-worker-0-dk4tp
kairos03-Pqx27-worker-0-gm7pn
kairos03-Pqx27-worker-0-lv6fs

# ===================================================================
# 6. EQUIPOS DE RED, APPLIANCES Y OTRAS PLATAFORMAS (Non-Linux Puros)
# ===================================================================

[storage_appliances]
hspeinas01.santpau.es ansible_user=hsproot ansible_password="{{ vault_pass_hsproot }}"
HSPEINAS02.santpau.es ansible_user=hsproot ansible_password="{{ vault_pass_hsproot }}"
HSPEINAS03.santpau.es ansible_user=hsproot ansible_password="{{ vault_pass_hsproot }}"
HSPEINAS04 ansible_user=hsproot ansible_password="{{ vault_pass_hsproot }}"
HSPEINAS05 ansible_user=hsproot ansible_password="{{ vault_pass_hsproot }}"
HSPEINAS06 ansible_user=hsproot ansible_password="{{ vault_pass_hsproot }}"
HSPEINAS07 ansible_user=hsproot ansible_password="{{ vault_pass_hsproot }}"
HSPEINAS08 ansible_user=hsproot ansible_password="{{ vault_pass_hsproot }}"

[other_distros]
BONEVIEW01 ansible_user=client ansible_password="{{ vault_pass_gleamer }}" ansible_become_pass="{{ vault_pass_gleamer }}"
#HSPEICONneCT01 ansible_user=Administrator ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
HSPEIGIT01 ansible_user=hsproot ansible_host=172.31.98.93 ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
HSPEICS. ansible_user=Administrator ansible_host=172.31.98.90
IRONPORT01
Ironport_CLON_20062024
#PYXIS01 ansible_user=instalador ansible_password="{{ vault_pass_instalador }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss' ansible_python_interpreter=/usr/bin/python2.7

[network_appliances]
CISCO-ISe01 ansible_user=admin
CISCO-ISe02 ansible_user=admin
FORTIWEB01 ansible_user=admin ansible_password="{{ vault_pass_fortiweb }}"
FORTIWEB02 ansible_user=admin ansible_password="{{ vault_pass_fortiweb }}"

[voice_infra]
cucmipccHSp.santpau.es ansible_user=administrator
CUCMIPCChsPS ansible_user=administrator
cucmpublISherhsp.santpau.es ansible_user=administrator
cucmsubsCRiberhsp.santpau.es ansible_user=administrator
cucmsubsCRiberhsp1.santpau.es ansible_user=administrator
cucmunitYHsp ansible_user=administrator

[vmware_infra]
vcsa01.santpau.es

[other_appliances]
carescapE01 ansible_user=service
MASIMODLms01 ansible_user=itsys ansible_password="{{ vault_pass_masimo }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
MASIMODMs01 ansible_user=itsys ansible_password="{{ vault_pass_masimo }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
MASIMOIG01 ansible_user=itsys ansible_password="{{ vault_pass_masimo }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
MASIMOIG01DES ansible_user=itsys ansible_password="{{ vault_pass_masimo }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
MASIMOPSn01 ansible_user=itsys ansible_password="{{ vault_pass_masimo }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
MASIMOPSn01DES ansible_user=itsys ansible_password="{{ vault_pass_masimo }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
MASIMOMCONT ansible_user=itsys ansible_password="{{ vault_pass_masimo }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
MASIMOMCONTDES ansible_user=itsys ansible_password="{{ vault_pass_masimo }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
MEDIPVITALS01 ansible_user=santpau ansible_password="{{ vault_pass_medip }}"
Panoramahsp01 ansible_password="{{ vault_pass_panorama }}"
SC4SSANTacREU ansible_host=172.31.99.111 ansible_user=mmtt ansible_password="{{ vault_pass_creu }}"
SYCONNECT01 ansible_user=syconnect
SYCONNECT02 ansible_user=syconnect

# ===================================================================
# 7. CATEGORÍAS ADICIONALES (Legacy, Apagados, Estado Indefinido)
# ===================================================================

[poweroff]
jartum
Enquesta01
IPQUORUM03_CONTINGENCIA_DATASTORELOCAL
IPQUORUM04_CONTINGENCIA_DATASTORELOCAL
znat
gambella
CISCO-ISE01_CONTINGENCIA
CISCO-ISE02_CONTINGENCIA
# Comentadas o dadas de baja temporalmente en desarrollo para evitar ruidos
#gota04deS
#openlab01Des
#PETITSACASA01DES
#petitsacASa01des
#petitsacASa02des
#trak03deS
#trak06deS

[NO_INFO]
csgmsrchDSp
gwp01 ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
SSM01.saNTpau.es ansible_user=admin ansible_password="{{ vault_pass_ssm01 }}"

[Version_antigua_python]
Auckland ansible_password="{{ vault_pass_default }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss' ansible_python_interpreter=/usr/bin/python2.7
barcelones ansible_user=root ansible_password="{{ vault_pass_default }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss' ansible_python_interpreter=/usr/bin/python2.7
patrim1.SAntpau.es ansible_password="{{ vault_pass_cisavic }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'

[no_python]
Intranet02 ansible_password="{{ vault_pass_default }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
Intranet01 ansible_password="{{ vault_pass_default }}" ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'

[unknown]
SHD-SKYLinE
HSPEIXERo01.santpau.es ansible_user=hsproot ansible_password="{{ vault_pass_hsproot }}" ansible_become_pass="{{ vault_pass_hsproot }}" ansible_host=172.31.88.89

[BAJA]
mirth02
mirth02dES
dns03

[AGFA]
HSPEIDBTEST.82 ansible_host=172.31.98.74
HSPEIGP01
HSPEIWSTesT.santpau.es ansible_user=hsproot ansible_password="{{ vault_pass_hsproot }}" ansible_become_pass="{{ vault_pass_hsproot }}" ansible_host=172.31.98.50

[NO_becomeSUDO]
appinfurG01des ansible_user=athenea ansible_password="{{ vault_pass_athenea }}" ansible_become_pass="{{ vault_pass_athenea }}"

[OBSOLETA]
iptv01deS ansible_user=iptv01desadm ansible_password="{{ vault_pass_iptv }}" ansible_become_pass="{{ vault_pass_iptv }}"

# ===================================================================
# 8. METAGRUPOS (Estructura de ejecución jerárquica)
# ===================================================================

[linux_vms:children]
linux_prod
linux_prod_faltantes
linux_des
linux_des_faltantes


[all_vms:children]
linux_vms
other_distros

[non_linux:children]
other_distros
network_appliances
voice_infra
storage_appliances
vmware_infra


# ===================================================================
# 9. GRUPOS DE BASES DE DATOS (Para sincronización estricta con SUMA)
# ===================================================================

[bbdd_des]
patwindb02des
setdb01dES
dwh01des
dwh02des
jirahspbD-test
mongodb01Des
mongodb02Des
mongodb03Des
mongodb04Des
mongodbdES
famaafm02Des

[bbdd_prod]
bbddspauA01
patwindb02
informesDB01
redcapdb01
jirahspbD
HSPEIDB01.santpau.es
dwh01
dwh02
mongodb
mongodb01
mongodb02
mongodb03
mongodb04
openlab05
trak03
piddb
pipdb
piqdb
sapsolmaN01
other_appliances
srv-db-sTOrage-pifs


[linux_des_faltantes]
omiq01des
omiq01sqldes
movisalud01des
webpub05des ansible_password="{{ vault_pass_webpub }}"
intranethsp03des
jirahsp-test

[linux_prod_faltantes]
speas01
speas02
speas03
speas04
speas05
speas06
spadb
spbdb
spedb
spfdb
spudb
omiq01
omiq01sql
movisalud01
movisaludbd01
movisaludinv01
movisaludinvsql
webpub05 ansible_password="Krn5jk2"
intranethsp03
webhsp04
sonarqube01
suse-sb1
promisedland01
exhsp-proxy-pass-int-2026
