[linux_servers]
app-nnn
appinfurg01
appinfurg01des
appwmp01
atb01
backbox01
bacteriemies01
bastion01
bastion03
bbddspaua01
boneview01
carescape01
codiasshsp
codiasshsp02
dlab01
enigmaprn03
etccons01
famaafm02-new
fortiauth01
fortiauth02
fortiweb01
fortiweb02
gestprj01
gitlab01
hspeinas06
informesdb01
intranethsp04
ise01
ise02
jenkins01
jirahsp
jirahspbd
jumpboxedr01
masimodlms01
masimodms01
masimoig01
masimoig01des
masimomcont
masimomcontdes
masimopsn01
masimopsn01des
mirth02
mirth02des
mongodb
mongodb01
mongodb01des
mongodb02
mongodb02des
mongodb03
mongodb03des
mongodb04
mongodb04des
mongodbdes
moodle
nexus01
nfsserver01
nfsserver02
opsmanager01
panoramahsp01
patwindb02des
redis01
sapbo05pre
sapcconnect01
sentry01
sescli01
sescli01des
setapp01
setdb01
shukun
sonarqube01
srv-db-storage-pifs
srv-web-api-pifs
sycai01
syconnect01
syconnect02
tarif04
webpub04
xicvar01

servidor-app-01 ansible_host=192.168.1.50
servidor-db-01 ansible_host=192.168.1.51

[all:vars]
;ansible_python_interpreter=/usr/bin/python3
ansible_user=root
;ansible_ssh_private_key_file=/ruta/a/tu/clave.pem
