# Inventario generado el Thu Dec 18 10:28:33 AM CET 2025
#BONEVIEW01 ansible_user="client" ansible_become_password=welcome2gleamer
#commvault-frel.santpau.es ansible_user="root"
#exhsp-proxy-pass ansible_user="root"
#famaafm02 ansible_user="root"
#foreman01 ansible_user="root"
#gestioip ansible_user="logicalis" ansible_become_password=2l$O-gvM
#HSPEIDB01.santpau.es ansible_user="hsproot" ansible_become_password=HSP2023Ch4ngePleas3+
#hspeinas01.santpau.es ansible_user="hsproot" ansible_become_password=HSP2023Ch4ngePleas3+
#HSPEINAS02.santpau.es ansible_user="hsproot" ansible_become_password=HSP2023Ch4ngePleas3+
#HSPEINAS03.santpau.es ansible_user="hsproot" ansible_become_password=HSP2023Ch4ngePleas3+
#HSPEINAS04 ansible_user="hsproot" ansible_become_password=HSP2023Ch4ngePleas3+
#HSPEINAS05.santpau.es ansible_user="hsproot" ansible_become_password=HSP2023Ch4ngePleas3+
#HSPEIWSTEST.santpau.es ansible_user="hsproot" ansible_become_password=HSP2023Ch4ngePleas3+
#HSPEIXERO02.santpau.es ansible_user="hsproot" ansible_become_password=HSP2023Ch4ngePleas3+
#jartum ansible_user="root"
#jirahsp ansible_user="root"
#jirahspbd-test ansible_user="root"
#MASIMOPSN01 ansible_user="itsys" #No existen credenciales.
#proxypass01 ansible_user="root"
#pyxisgr01.santpau.es ansible_user="installer" ansible_become_password=1nStA11Er'
#QUENDAANBLICK ansible_user="root"
#redcapapp01 ansible_user="root"
#redcapdb01 ansible_user="root"
#smovil03 ansible_user="root" ansible_become_password=SmoVil17 #No instala agente
#SSM01.santpau.es ansible_user="admin"
#sw-backups ansible_user="root"
#syconnect01 ansible_user="syconnect"
#webapps01 ansible_user="root"
#medipvitals01 ansible_user=santpau ansible_become_password=DoihEa4Z
#ipquorum04-1 ansible_user=root ansible_become_password=IPQ2021
#ipquorum03-1 ansible_user=root  ansible_become_password=IPQ2021
#CISCO-ISE01 ansible_user="admin" ansible_become_password=HN5ScqwmKgPU6QkC #CISCO
#CISCO-ISE02 ansible_user="admin" ansible_become_password=HN5ScqwmKgPU6QkC #CISCO
#hspeibi01.santpau.es ansible_user="hsproot" ansible_become_password=HSP2023Ch4ngePleas3+
