# ===================================================================
# GRUPOS DE VARIABLES
# ===================================================================
# Variables que aplican a [all] (todos los hosts)
[all:vars]
;ansible_ssh_private_key_file=/ruta/a/tu/clave.pem

# Variables que aplicarán a [linux_servers] y [k8s_nodes]
# El usuario 'root' por defecto se aplica solo a los Linux
# que no tengan un ansible_user específico
[linux_vms:vars]
ansible_user=root
ansible_become_pass=2l$O-gvM
;ansible_python_interpreter=/usr/bin/python3

# ===================================================================
# GRUPOS DE HOSTS (Clasificación)
# ===================================================================
# Hosts que parecen ser servidores Linux estándar
[linux_servers]
activiti01   ansible_user=atos ansible_password=1.santpau ansible_become_pass=1.santpau
ansible01
appinfurG01 ansible_user=athenea ansible_password=4th3nea.hsp ansible_become_pass=4th3nea.hsp
appinfurG01des ansible_user=athenea ansible_password=4th3nea.hsp ansible_become_pass=4th3nea.hsp
app-nnn
appwmp01
arum01
atb01 ansible_host=172.31.88.204 ansible_password=2l$O-gvM
bastion01 ansible_host=172.33.105.105 ansible_user=oke-admin ansible_password=root1234 ansible_become_pass=root1234
bastion02
bastion03
bbddspauA01
cisco-sySLog01 ansible_password=2l$O-gvM
codiasshSP01
codiasshSP02
commvaulT-frel.santpau.es
dlab01 ansible_user=logicalis ansible_password=2l$O-gvM
dna-backUPs
dns01
dns02
dns03
dns04
dns05
dokuflex01
dokuflex01cons.santpau.es
dokuflex01test
dwh01
dwh01des
dwh02
dwh02des
ritmocorE.santpau.es
enigma01DEs
enigmaprN03
estimtraCK01.santpau.es
estimtraCK01des.santpau.es
etccons01
exhsp-prOXy-pass
exhsp-prOXy-pass-int
exhsp-prOXy-pass-int-clone ansible_host=172.31.99.82 ansible_password=2l$O-gvM ansible_become_pass=2l$O-gvM
famaafm02
famaafm02Des
famaapp01
famaapp01Des
foreman01
ftp01
gefact02
gestioip ansible_user=logicalis
gestionlOGs  ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss' ansible_password=2l$O-gvM
gestprj01
gitlab01
gota04
gota04deS
hspeibi01.santpau.es ansible_user=hsproot ansible_password=HSP2023Ch4ngePleas3+ ansible_become_pass=HSP2023Ch4ngePleas3+
HSPEIDB01.santpau.es  ansible_user=hsproot ansible_password=HSP2023Ch4ngePleas3+ ansible_become_pass=HSP2023Ch4ngePleas3+
HSPEIWSTesT.santpau.es ansible_user=hsproot ansible_password=HSP2023Ch4ngePleas3+ ansible_become_pass=HSP2023Ch4ngePleas3+ ansible_host=172.31.98.50
HSPEIXERo02.santpau.es ansible_user=hsproot ansible_password=HSP2023Ch4ngePleas3+ ansible_become_pass=HSP2023Ch4ngePleas3+ ansible_host=172.31.98.72
informesDB01
intrahsp01
intrahsp01des
intrahsp02
intrahsp02des
intrahsp03
intrahsp03des ansible_password=3c4n5s.2019 ansible_become_pass=3c4n5s.2019
intrahsp04 ansible_password=3c4n5s.2019 ansible_become_pass=3c4n5s.2019
intrahsp04des ansible_password=3c4n5s.2019 ansible_become_pass=3c4n5s.2019
intranetHSp04
ipquorum03 ansible_password=IPQ2021 ansible_host=172.31.91.189
ipquorum04 ansible_password=IPQ2021 ansible_host=172.31.91.190
iptv01deS  ansible_user=iptv01desadm ansible_password=admiptv01des ansible_become_pass=admiptv01des
jenkins01
jirahsp
jirahspbD
jirahspbD-test
jirahsp-TEst
mirth02
mirth02dES
mongodb
mongodb01
mongodb01Des
mongodb02
mongodb02Des
mongodb03
mongodb03Des
mongodb04
mongodb04Des
mongodbdES
moodle
MYSQL01
nagios.sANtpau.es
nexus01
omaweb01.Santpau.es
openlab01
openlab01Des
openlab05
openlab08
opsmanagER01
patwindb02
patwindb02des
PETITSACASA01    ansible_password=2l$O-gvM ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
PETITSACASA01DES 
petitsacASa01des
petitsacASa02 ansible_password=2l$O-gvM ansible_become_pass=2l$O-gvM ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
petitsacASa02des
pid01
piddb
pip01
pipdb
piq01
piqdb
proxy-paSS
proxypasS01
proxy-paSS-ir
puigmal
puigsacaLM
pyxisgr01.santpau.es ansible_user=installer ansible_become_pass="1nStA11Er'"
QUENDAANblICK
recerca02 ansible_user=recerca ansible_become_pass=r3c3rc4.hsp
redcapapP01
redcapdb01
redis01
rman01
rman19
sapcconnECt01
sapsolmaN01
sapspa01
sapspb01
sapspe
sapspf01
sapspp01
sapspu01
sau01 ansible_user=atos ansible_become_pass=1.santpau
sau01des ansible_user=atos ansible_become_pass=1.santpau
scannessUS01 ansible_user=admsechsp ansible_password=Hsp$01Sec ansible_become_pass=Hsp$01Sec
sentry01 ansible_host=172.33.106.16
sescli01
sescli01DEs
setapp01
setapp01DEs
setdb01
setdb01dES
SHUKUN                             ansible_user=logicalis_adm ansible_password=2l$O-gvM         
smovil03
sonarqubE01
spadb
spbdb
speas01
speas02
speas03
speas04
speas05
speas06
spedb
spfdb
sppdb
spudb
srv-db-sTOrage-pifs
srv-web-APi-pifs
stor2rrd01
susemanaGEr01
sw-backuPS
sycai01
taonet02
tarif04
#teampass01
trak03
trak03deS
trak06deS
UBUNTU01          ansible_password=1.santpau                 ansible_user=atos ansible_become_pass=1.santpau
wdisp01dES
wdisp01pRO
webapps01 
webapps01Des ansible_user=webapps ansible_password=webapps ansible_become_pass=webapps
webir01
webir02
webpub01
webpub01DEs
webpub02
webpub02DEs
webpub03
webpub04
xicvar01
zabbix01
developmENt03 ansible_user=atos ansible_password=1.santpau ansible_become_pass=1.santpau # Probablemente Linux

[poweroff]
jartum

[NO_INFO]
csgmsrchDSp
gwp01 ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss' 
SSM01.saNTpau.es ansible_user=admin ansible_password=T3l1ndu$T3l1ndu$

[Version_antigua_python]
Auckland  ansible_password=2l$O-gvM ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss' ansible_python_interpreter=/usr/bin/python2.7
barcelones ansible_user=root ansible_password=2l$O-gvM ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss' ansible_python_interpreter=/usr/bin/python2.7
patrim1.SAntpau.es ansible_password=cisavic ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'

# Hosts que parecen ser Nodos de Kubernetes
[k8s_nodes]
dev-oke-BKf7c-master-0 ansible_host=172.33.105.27
dev-oke-BKf7c-master-1   ansible_host=172.33.105.28
dev-oke-BKf7c-master-2   ansible_host=
dev-oke-BKf7c-worker-bktqf   ansible_host=
dev-oke-BKf7c-worker-fvgvw   ansible_host=
kairos02-Bqfh8-infra-lwbz7
kairos02-Bqfh8-infra-qk2cl
kairos02-Bqfh8-infra-qmkhq
kairos02-Bqfh8-master-0
kairos02-Bqfh8-master-1
kairos02-Bqfh8-master-2
kairos02-Bqfh8-worker-mdbll
kairos02-Bqfh8-worker-mlnz5
kairos02-Bqfh8-worker-rqsdw
kairos02-Bqfh8-worker-zjvgt
kairos03-Pqx27-infra-76pcv
kairos03-Pqx27-infra-dzcfc
kairos03-Pqx27-infra-m9sg7
kairos03-Pqx27-master-0
kairos03-Pqx27-master-1
kairos03-Pqx27-master-2
kairos03-Pqx27-worker-0-85hcr
kairos03-Pqx27-worker-0-dk4tp
kairos03-Pqx27-worker-0-gm7pn
kairos03-Pqx27-worker-0-lv6fs

# Hosts que parecen ser Windows (por ansible_user)
[other_distros]
BONEVIEW01 ansible_user=client ansible_password=welcome2gleamer ansible_become_pass=welcome2gleamer #fedora SECUREBOOT DESACTIVADO
HSPEICONneCT01 ansible_user=Administrator ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss' #No existe password Oracle Linux
HSPEIGIT01  ansible_user=hsproot ansible_host=172.31.98.93 ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
HSPEICS.SAntpau.es ansible_user=Administrator ansible_host=172.31.98.90

# Appliances de Red (Cisco, Fortinet)
[network_appliances]
CISCO-ISe01 ansible_user=admin	
CISCO-ISe02 ansible_user=admin
#FortiAutHEnticator-VM01
#FortiAutHEnticator-VM01
FORTIWEB01 ansible_user=admin ansible_password=MnGlSaDrWQ
FORTIWEB02 ansible_user=admin ansible_password=MnGlSaDrWQ

# Appliances de Voz (Cisco Call Manager)
[voice_infra]
cucmipccHSp.santpau.es ansible_user=administrator
CUCMIPCChsPS ansible_user=administrator
cucmpublISherhsp.santpau.es ansible_user=administrator #No password
cucmsubsCRiberhsp.santpau.es ansible_user=administrator
cucmsubsCRiberhsp1.santpau.es ansible_user=administrator
cucmunitYHsp ansible_user=administrator

# Appliances de Almacenamiento (NAS)
[storage_appliances]
hspeinas01.santpau.es ansible_user=hsproot ansible_password=HSP2023Ch4ngePleas3+
HSPEINAS02.santpau.es ansible_user=hsproot ansible_password=HSP2023Ch4ngePleas3+
HSPEINAS03.santpau.es ansible_user=hsproot ansible_password=HSP2023Ch4ngePleas3+
HSPEINAS04 ansible_user=hsproot ansible_password=HSP2023Ch4ngePleas3+
HSPEINAS05.santpau.es ansible_user=hsproot ansible_password=HSP2023Ch4ngePleas3+
HSPEINAS06 ansible_user=hsproot ansible_password=HSP2023Ch4ngePleas3+
HSPEINAS07.santpau.es ansible_user=hsproot ansible_password=HSP2023Ch4ngePleas3+
HSPEINAS08.santpau.es ansible_user=hsproot ansible_password=HSP2023Ch4ngePleas3+

# Infraestructura de VMware
[vmware_infra]
vcsa01.santpau.es

# Otros Appliances (Masimo, Medip, Panorama, Splunk, etc.)
[other_appliances]
carescapE01 ansible_user=service
MASIMODLms01  ansible_user=itsys ansible_password=vRYEqJL8AHZ@fXa! ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
MASIMODMs01  ansible_user=itsys ansible_password=vRYEqJL8AHZ@fXa! ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
MASIMOIG01  ansible_user=itsys ansible_password=vRYEqJL8AHZ@fXa! ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
MASIMOIG01DES  ansible_user=itsys ansible_password=vRYEqJL8AHZ@fXa! ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
MASIMOPSn01  ansible_user=itsys ansible_password=vRYEqJL8AHZ@fXa! ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
MASIMOPSn01DES  ansible_user=itsys ansible_password=vRYEqJL8AHZ@fXa! ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
MASIMOMCONT                        ansible_user=itsys ansible_password=vRYEqJL8AHZ@fXa! ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'         
MASIMOMCONTDES                     ansible_user=itsys ansible_password=vRYEqJL8AHZ@fXa! ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'         
#medipvitALs
MEDIPVITALS01                      ansible_user=santpau ansible_password=DoihEa4Z         
Panoramahsp01 ansible_password=Axians01.
SC4SSANTacREU ansible_host=172.31.99.111,ansible_user=mmtt,ansible_password=Creu.01
SYCONNECT01                        ansible_user=syconnect
SYCONNECT02                        ansible_user=syconnect

# Hosts que no he podido clasificar
[unknown]
SHD-SKYLinE
HSPEIXERo01.santpau.es ansible_user=hsproot ansible_password=HSP2023Ch4ngePleas3+ ansible_become_pass=HSP2023Ch4ngePleas3+ ansible_host=172.31.98.89 #NO password


# ===================================================================
# METAGRUPOS (Grupos de Grupos)
# ===================================================================

# ¡¡ESTE ES EL GRUPO QUE NECESITAS USAR!!
# Contiene solo las VMs de Linux
[linux_vms:children]
linux_servers
k8s_nodes

# Un grupo para todas las VMs (Linux + Windows)
[all_vms:children]
linux_vms
other_distros

# Un grupo para todos los dispositivos que NO son Linux
[non_linux:children]
other_distros
network_appliances
voice_infra
storage_appliances
vmware_infra
other_appliances
unknown
local

[no_python]
Intranet02  ansible_password=2l$O-gvM ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
Intranet01 ansible_password=2l$O-gvM ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss' 
#Intranet01:~ # ls /sys/firmware/
#acpi  edd
#Secure Boot está 100% desactivado en Intranet01

# Ansible crea automáticamente el grupo [all] que contiene TODO
