---
- name: 1. Auditar y Guardar Estado (en cada host remoto)
  hosts: all
  gather_facts: yes # Necesitamos los 'facts'
  # Ignora los hosts que no se pueden conectar
  ignore_unreachable: true 
  ignore_errors: true

  tasks:
    - name: Determinar el estado de Secure Boot
      set_fact:
        secureboot_status: >-
          {% if ansible_facts.efi is defined and ansible_facts.efi.secureboot is defined %}
          {{ ansible_facts.efi.secureboot }}
          {% elif ansible_facts.efi is defined %}
          NO_SE_PUDO_VERIFICAR
          {% else %}
          NO_EFI (Modo BIOS/Legacy)
          {% endif %}

    - name: Guardar el resultado en /tmp/ del host remoto
      copy:
        # Escribe solo el estado en un fichero temporal
        content: "{{ secureboot_status }}"
        dest: "/tmp/secureboot_status.txt"
