[all:vars]
ansible_user=root
ansible_become_pass=2l$O-gvM
;ansible_python_interpreter=/usr/bin/python3

[all]
carescape01	ansible_host=1723188135
BONEVIEW01	ansible_host=172.31.50.191

csgmsrchdsp ansible_host=172.31.88.104
alinity02.santpau.es ansible_host=172.31.88.24
CISCO-ISE01	ansible_host=1723150108
CISCO-ISE02	ansible_host=1723150109
commvault-frel.santpau.es	ansible_host=1723150164
cucmipcchsp.santpau.es	ansible_host=172312008
CUCMIPCCHSPS	ansible_host=1723120018
cucmpublisherhsp.santpau.es	ansible_host=172312004
cucmsubscriberhsp.santpau.es	ansible_host=172312005
cucmsubscriberhsp1.santpau.es	ansible_host=172312006
cucmunityhsp	ansible_host=172312007
dev-oke-bkf7c-master-0	ansible_host=1723310527
dev-oke-bkf7c-master-1	ansible_host=1723310528
dev-oke-bkf7c-master-2	ansible_host=1723310529
dev-oke-bkf7c-worker-bktqf	ansible_host=1723310530
dev-oke-bkf7c-worker-fvgvw	ansible_host=1723310531
enquesta01	
exhsp-proxy-pass	ansible_host=848818325
exhsp-proxy-pass-int-clone	ansible_host=172319982
famaafm02	ansible_host=1723188235
foreman01	ansible_host=172319971
gambela	
gestioip	ansible_host=1723199242
hspeibi01.dspau.santpau.es	ansible_host=172319851
HSPEICONNECT01	ansible_host=172319892
HSPEICS.santpau.es	ansible_host=172319890
HSPEIDB01.santpau.es	ansible_host=172319870
HSPEIDBSTEST.dspau.santpau.es	ansible_host=172319874
HSPEIGIT01	ansible_host=172319893
localhost.localdomain	ansible_host=72319897
hspeinas01.santpau.es	ansible_host=72319891
HSPEINAS02.santpau.es	ansible_host=72319884
HSPEINAS03.santpau.es	ansible_host=72319894
HSPEINAS04	ansible_host=172319895
HSPEINAS05.santpau.es	ansible_host=172319896
HSPEINAS06	ansible_host=1723198100
HSPEINAS07.santpau.es	ansible_host=723198120
HSPEINAS08.santpau.es	ansible_host=72319880
HSPEIWSTEST.santpau.es	ansible_host=72319850
HSPEIXERO01.santpau.es	ansible_host=72319889
HSPEIXERO02.santpau.es	ansible_host=72319872
intrahsp04	
ipquorum03	ansible_host=1723191189
ipquorum04	ansible_host=1723191190
jartum	
jirahsp	ansible_host=172315514
jirahspbd-test	ansible_host=1723199134
kairos02-bqfh8-infra-lwbz7	ansible_host=723310623
kairos02-bqfh8-infra-qk2cl	ansible_host=723310621
kairos02-bqfh8-infra-qmkhq	ansible_host=723310622
kairos02-bqfh8-master-0	ansible_host=723310634
kairos02-bqfh8-master-1	ansible_host=723310633
kairos02-bqfh8-master-2	ansible_host=723310635
kairos02-bqfh8-worker-mdbl	ansible_host=102122
kairos02-bqfh8-worker-mlnz	ansible_host=10282
kairos02-bqfh8-worker-rqsd	ansible_host=102102
kairos02-bqfh8-worker-zjvg	ansible_host=102202
kairos03-pqx27-infra-76pcv	ansible_host=103182
kairos03-pqx27-infra-dzcfc	ansible_host=103202
kairos03-pqx27-infra-m9sg7	ansible_host=103162
kairos03-pqx27-master-0	ansible_host=10302
kairos03-pqx27-master-1	ansible_host=10322
kairos03-pqx27-master-2	ansible_host=10342
kairos03-pqx27-worker-0-85hcr	ansible_host=172.33.10727
kairos03-pqx27-worker-0-dk4tp	ansible_host=172.33.10729
kairos03-pqx27-worker-0-gm7pn	ansible_host=172.33.10728
kairos03-pqx27-worker-0-lv6fs	ansible_host=172.33.10730
MASIMODLMS01	ansible_host=172.31.50.7
MASIMODMS01	ansible_host=172.31.88.214
MASIMOIG01	ansible_host=172.31.50.9
MASIMOIG01DES	ansible_host=172.31.99.131
MASIMOPSN01	ansible_host=172.31.50.8
MASIMOPSN01DES	ansible_host=172.31.99.88
medipvitals	ansible_host=172.31.88.245
Panorama	ansible_host=172.31.55.50
proxypass01	ansible_host=172.31.99.115
pyxisgr01.santpau.es	ansible_host=172.31.50.173
QUENDAANBLICK	ansible_host=172.31.50.186
redcapapp01	ansible_host=172.31.88.56
redcapdb01	ansible_host=172.31.88.55
smovil03	ansible_host=172.31.88.237
SSM01.santpau.es	ansible_host=172.31.88.175
sw-backups	ansible_host=172.31.88.60
syconnect01	ansible_user=syconnect ansible_host=172.31.55.29 
teampass01	
webapps01	ansible_host=1723188158

